apiVersion: v1
kind: Service
metadata:
  name: {{ include "mox.fullname" . }}
  labels:
    {{- include "mox.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- range .Values.service.ports }}
    - port: {{ . }}
      targetPort: tcp-{{ . }}
      protocol: TCP
      name: tcp-{{ . }}
    {{- end }}
  selector:
    {{- include "mox.selectorLabels" . | nindent 4 }}
