---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "roundcubemail.fullname" . }}
  labels:
    {{- include "roundcubemail.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  strategy:
    {{ .Values.deployment.strategy | toYaml | nindent 4 }}
  selector:
    matchLabels:
      {{- include "roundcubemail.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "roundcubemail.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.deployment.initContainers }}
      initContainers:
        {{- with .Values.deployment.initContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      serviceAccountName: {{ include "roundcubemail.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: roundcubemail
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}-fpm-alpine"
          imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
          command:
            - /bin/bash
          args:
            - "-c"
            - "{{ include "roundcube.deployment.command" . }}"
          env:
            - name: ROUNDCUBEMAIL_DEFAULT_HOST
              value: "{{ include "roundcube.encryption" .Values.imap.encryption }}{{ required "no IMAP host defined" .Values.imap.host }}"
            - name: ROUNDCUBEMAIL_DEFAULT_PORT
              value: "{{ .Values.imap.port }}"
            - name: ROUNDCUBEMAIL_SMTP_SERVER
              value: "{{ include "roundcube.encryption" .Values.smtp.encryption }}{{ required "no SMTP host defined" .Values.smtp.host }}"
            - name: ROUNDCUBEMAIL_SMTP_PORT
              value: "{{ .Values.smtp.port }}"
            - name: ROUNDCUBEMAIL_SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "roundcubemail.fullname" . }}
                  key: smtpUsername
            - name: ROUNDCUBEMAIL_SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "roundcubemail.fullname" . }}
                  key: smtpPassword
            - name: ROUNDCUBEMAIL_DES_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "roundcubemail.fullname" . }}
                  key: desKey
            - name: ROUNDCUBEMAIL_LANGUAGE
              value: "{{ .Values.config.defaultLanguage }}"
            - name: ROUNDCUBEMAIL_PLUGINS
              value: "{{ include "roundcube.plugins.list" . }}"
            - name: ROUNDCUBEMAIL_SKIN
              value: "{{ .Values.config.defaultSkin }}"
            - name: ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE
              value: "{{ .Values.config.uploadMaxFilesize }}"
            {{- if eq .Values.database.source "external" }}
            - name: ROUNDCUBEMAIL_DB_TYPE
              value: "{{ .Values.externalDatabase.type }}"
            - name: ROUNDCUBEMAIL_DB_HOST
              value: "{{ required "No database host configured" .Values.externalDatabase.host }}"
            - name: ROUNDCUBEMAIL_DB_PORT
              value: "{{ .Values.externalDatabase.port }}"
            - name: ROUNDCUBEMAIL_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "roundcubemail.fullname" . }}
                  key: dbUsername
            - name: ROUNDCUBEMAIL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "roundcubemail.fullname" . }}
                  key: dbPassword
            - name: ROUNDCUBEMAIL_DB_NAME
              value: "{{ .Values.externalDatabase.name }}"
            {{- else if eq .Values.database.source "zalando-postgres" }}
            - name: ROUNDCUBEMAIL_DB_TYPE
              value: pgsql
            - name: ROUNDCUBEMAIL_DB_HOST
              value: "{{ include "roundcubemail.fullname" . }}-db"
            - name: ROUNDCUBEMAIL_DB_PORT
              value: "5432"
            - name: ROUNDCUBEMAIL_DB_USER
              valueFrom:
                secretKeyRef:
                  name: "roundcube-owner-user.{{ include "roundcubemail.fullname" . }}-db.credentials.postgresql.acid.zalan.do"
                  key: username
            - name: ROUNDCUBEMAIL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "roundcube-owner-user.{{ include "roundcubemail.fullname" . }}-db.credentials.postgresql.acid.zalan.do"
                  key: password
            - name: ROUNDCUBEMAIL_DB_NAME
              value: roundcube
            {{- end }}
            - name: COMPOSER_ALLOW_SUPERUSER
              value: "1"
          volumeMounts:
            - name: config
              mountPath: /usr/local/etc/php/conf.d/zzz-custom.ini
              subPath: php.ini
            - name: config
              mountPath: /var/roundcube/config/custom.php
              subPath: roundcube.config.php
            - name: config
              mountPath: /usr/local/etc/php-fpm.d/zzz-custom.conf
              subPath: php-fpm.conf
            - name: shared-files
              mountPath: /var/www/html
          {{ if .Values.deployment.resources }}
          resources: {{ .Values.deployment.resources | toYaml | nindent 12 }}
          {{ end }}
        - name: nginx
          image: {{ .Values.deployment.containers.nginx.image }}
          imagePullPolicy: {{ .Values.deployment.containers.nginx.imagePullPolicy }}
          volumeMounts:
            - name: shared-files
              mountPath: /var/www/html
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          ports:
            - containerPort: {{ .Values.deployment.port }}
              protocol: TCP
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 2
            periodSeconds: 3
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 2
            periodSeconds: 3
            initialDelaySeconds: 5
            failureThreshold: 3
      imagePullSecrets:
      {{- range .Values.deployment.imagePullSecrets }}
        - name: {{ .name }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "roundcubemail.fullname" . }}
        - name: shared-files
          emptyDir: {}
