---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "roundcubemail.fullname" . }}
  labels:
    {{- include "roundcubemail.labels" . | nindent 4 }}
type: Opaque
stringData:
  smtpUsername: "{{ .Values.smtp.username }}"
  smtpPassword: "{{ .Values.smtp.password }}"
  dbUsername: "{{ .Values.externalDatabase.user }}"
  dbPassword: "{{ .Values.externalDatabase.password }}"
  desKey: "{{ include "roundcube.desKey" . }}"
